core/urls.py
from django.urls import path
from .views import HomeTemplateView
from django.conf.urls import url
from core import views


app_name = 'core'


urlpatterns = [
    path('', HomeTemplateView.as_view()),
    url(r'^home$', views.home, name='home'),
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    path('allblogs/', views.allblogs, name='allblogs'),
    path('<int:blog_id>/', views.detail, name="detail"),
]

portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    url(r'^$', views.home, name='home'),
    url(r'^special/', views.special, name='special'),
    url(r'^core/', include('core.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    path('allblogs/', views.allblogs, name='allblogs'),
    path('<int:blog_id>/', views.detail, name="detail"),



                  # include our custom app urls here
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

from django.db import models
from django.contrib.auth.models import User


# About Model
class About(models.Model):
    short_description = models.TextField()
    description = models.TextField()
    image = models.ImageField(upload_to="about")

    class Meta:
        verbose_name = "About me"
        verbose_name_plural = "About me"

    def __str__(self):
        return "About me"



# Service Model
class Service(models.Model):
    name = models.CharField(max_length=100, verbose_name="Service name")
    #description = models.TextField(verbose_name="About service")
    area = models.TextField(verbose_name="Working Area")
    Charge = models.CharField(max_length=10,verbose_name="Charges")
    image = models.ImageField(upload_to="services")
    def __str__(self):
        return self.name

    def area_as_list(self):
        return self.area.split(',')



# Recent Work Model
class RecentWork(models.Model):
    title = models.CharField(max_length=100, verbose_name="Work title")
    image = models.ImageField(upload_to="works")

    def __str__(self):
        return self.title


# Client model
class Client(models.Model):
    name = models.CharField(max_length=100, verbose_name="Client name")
    description = models.TextField(verbose_name="Client say")
    image = models.ImageField(upload_to="clients", default="default.png")

    def __str__(self):
        return self.name

#contact info
class Contact(models.Model):
    description = models.TextField(verbose_name="Contact/Address info")

    def __str__(self):
        return self.description

#All Tittles

class aboutTitle(models.Model):
    name = models.CharField(max_length=100, verbose_name="Enter About Title")

    def __str__(self):
        return self.name

class serviceTitle(models.Model):
    name = models.CharField(max_length=100, verbose_name="Enter Service Title")

    def __str__(self):
        return self.name

class portfolioTitle(models.Model):
    name = models.CharField(max_length=100, verbose_name="Enter Portfolio Title")

    def __str__(self):
        return self.name

class testimonialTitle(models.Model):
    name = models.CharField(max_length=100, verbose_name="Enter Testimonial Title")

    def __str__(self):
        return self.name

class adressTitle(models.Model):
    name = models.CharField(max_length=100, verbose_name="Enter Address bar Title")

    def __str__(self):
        return self.name



class contactTitle(models.Model):
    name = models.CharField(max_length=100, verbose_name="Contact Title")

    def __str__(self):
        return self.name


class FooterText(models.Model):
    name = models.CharField(max_length=100, verbose_name="Add Footer Text")

    def __str__(self):
        return self.name

class SlideImage(models.Model):
    name1 = models.CharField(max_length=100, verbose_name="Images name 1")
    description1 = models.CharField(max_length=100, verbose_name="Images Description")
    image1 = models.ImageField(upload_to="slideimage")
    name2 = models.CharField(max_length=100, verbose_name="Images name 2")
    description2 = models.CharField(max_length=100, verbose_name="Images Description 2")
    image2 = models.ImageField(upload_to="slideimage")
    name3 = models.CharField(max_length=100, verbose_name="Images name 3")
    description3 = models.CharField(max_length=100, verbose_name="Images Description 3")
    image3 = models.ImageField(upload_to="slideimage")


    def __str__(self):
        return self.name1



class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    job = models.CharField(max_length=100, verbose_name="Service Name")
    o_date = models.CharField(max_length=100, verbose_name="Date of Order")
    d_date = models.CharField(max_length=100, verbose_name="Estimated Completion Date")
    fn = models.CharField(max_length=100, verbose_name="First name")
    ln = models.CharField(max_length=100, verbose_name="Last name")
    ads = models.CharField(max_length=100, verbose_name="Phone")

    status = models.CharField(max_length=100, verbose_name="Current Status")




    def __str__(self):
        return self.user.username


class Blog(models.Model):
    title = models.CharField(max_length=255)
    pub_date = models.DateTimeField()
    image = models.ImageField(upload_to='images/')
    body = models.TextField()
    update_at = models.TextField(null=True, blank=True)
    Developing_at = models.TextField(null=True, blank=True)
    Piloting_at = models.TextField(null=True, blank=True)
    Debug_at = models.TextField(null=True, blank=True)
    Ready_at = models.TextField(null=True, blank=True)

   # update = models.CharField(max_length=300, verbose_name="update")

    def summary(self):
        return self.body[:100]

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e, %Y')

    def __str__(self):
        return self.title

core/forms.py
from django import forms
from core.models import UserProfileInfo
from django.contrib.auth.models import User

class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('fn','ln','ads','portfolio_site','profile_pic')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

core/views.py
from django.views.generic import TemplateView
from .models import *
from django.shortcuts import render
from core.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required



from django.shortcuts import render, get_object_or_404
from .models import Blog



def home(request):
    return render(request, 'home.html')


@login_required
def special(request):
    return HttpResponse("You are logged in !")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request, 'core/registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username, password))
            return HttpResponse("Invalid login details given.Please Back to the Login page and Try again!")
    else:
        return render(request, 'core/login.html', {})







class HomeTemplateView(TemplateView):
    template_name = 'home.html'

    # override get context date method
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # first, call super get context data
        context['about'] = About.objects.first()
        context['services'] = reversed(Service.objects.all())
        context['works'] = RecentWork.objects.all()
        context['clients'] = Client.objects.all()
        context['contact'] = Contact.objects.first()
        context['contactT'] = contactTitle.objects.first()
        context['aboutT'] = aboutTitle.objects.first()
        context['clientsT'] = testimonialTitle.objects.first()
        context['servicesT'] = serviceTitle.objects.first()
        context['portfolioT'] = portfolioTitle.objects.first()
        context['addressT'] = adressTitle.objects.first()
        context['footer'] = FooterText.objects.first()
        context['slideimage'] = SlideImage.objects.first()





        return context


def allblogs(request):
    blogs = Blog.objects
    return render(request, 'core/allblogs.html', {'blogs': blogs})


def detail(request, blog_id):
    blogdetail = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'core/detail.html', {'blog': blogdetail})

templates/core/allblogs.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ema</title>
    {% include 'includes/stylesheets.html' %}
</head>
<body>

<div class="loader_bg">
    <div class="loader"></div>
</div>



<nav class="navbar navbar-custom navbar-fixed-top">
    <div class="container">
        {% load static %}
              <img src="{% static 'image\lg.png' %}" style="width:5%;height:22">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="/"> </a>
        </div>
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <li><a class="navbar-link" href="{% url 'home' %}">Home</a></li>







            </ul>
        </div>
    </div>
</nav>




<div class="container">
    <div class="jumbotron">


      		<h1>Projets</h1>
      		<br /> <br />
     		 <h2>Latest Project</h2>
     		 <hr/>
     		 {% for blog in  blogs.all %}
    			<a href="{% url 'detail' blog.id %}">  <h3>{{ blog.title }}</h3></a>
   			   {{ blog.pub_date_pretty }}
   			   <br />
    			  <img src = "{{ blog.image.url }}" height=200 width=200/>
  			    <br />
    			  <p>{{ blog.summary }}</p>
     		 {% endfor %}



</div>
  </div>

{% include 'includes/scripts.html' %}
<style>


.label {
    display: inline-block;
    max-width: 100%;
    margin-bottom: 5px;
    font-weight: 700;
    color: #191424;
}
p {
    line-height: 26px;
    font-size: 14px;
    font-weight: 400;
    color: #2d2938;
}



.jumbotron {
  position: absolute;
    left: 13%;
    top: 13%;
    width: 75%;
    text-align: left;
    font-size: 20px;
    padding-top: 30px;
    padding-bottom: 30px;
    margin-bottom: 30px;
    color: inherit;
    background-color: #875690;
    border: 1px solid #ccc;
    border-radius: 9px;
    box-sizing: border-box;
    background-image: url("https://cdn.pixabay.com/photo/2016/04/15/04/02/water-1330252_1280.jpg");
}

body {
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 14px;
    line-height: 1.42857143;

        color: #f5f5f5;
    background-color: #fff8d7;
    background-image: url("https://www.masslibsystem.org/wp-content/uploads/backgrounds-blank-blue-953214.jpg");
    }

@media(min-width:768px) {
    .navbar-custom {
        padding: 4px 0;
        border-bottom: 0;
        letter-spacing: 1px;
        background: rgba(0,0,0,.075);
        -webkit-transition: background .5s ease-in-out, padding .5s ease-in-out;
        -moz-transition: background .5s ease-in-out, padding .5s ease-in-out;
        transition: background .5s ease-in-out, padding .5s ease-in-out;
    }
    .navbar-custom.top-nav-collapse {
        -webkit-box-shadow: 0px 0px 2px #777;
        box-shadow: 0px 0px 2px #777;
        background-color: rgba(0, 0, 0, 1);
        box-shadow: 0px 0px 3px rgba(0, 0, 0, 1);
    }
    .navbar-custom.top-nav-collapse .nav li a {
        color: #fff;
    }
    .navbar-custom.top-nav-collapse .nav li.active a {
        background-color: transparent;
        color: #FF0000 !important;
    }
    .navbar-custom.top-nav-collapse .navbar-brand {
        color: #fff;
    }
}


 .navbar-custom .nav li a:hover {
    outline: 0;
    color: rgba(255, 255, 255, .8);
    background-color: #8B008B;
}

   .navbar-custom .nav li a:focus,
   .navbar-custom .nav li a:active {
    outline: 0;
    background-color: transparent;
}


.navbar-custom a {
    color: white;
    font-size: 13px;
    letter-spacing: 0px;
    font-weight: bold;
}
.navbar-custom.navbar-fixed-top.top-nav-collapse {
    background: #48034c;
}

.navbar-custom.top-nav-collapse .nav li a {
    color: #fff;
}

.navbar-custom {
    background: rgba(0,0,0,.075);
    border-bottom: none;
}

.footer-area{

    position: fixed;
    left: 0%;
    top: 92%;
    width: 100%;
    text-align: center;

}
.footer-area {
    background: #48034c;
    padding: 7px 0;
}

input, optgroup, select, textarea {
    margin: 0;
    font: inherit;
    color: black;
}
#snackbar {

  text-align: center; /* Centered text */

}


</style>


{% block content %}{% endblock %}

templates/core/details.html
<!doctype html>
<html>
  <head>
    <title> {{ blog.title }}</title>
  </head>
<body>
      <h1> {{ blog.title }}</h1>
          <p>{{ blog.pub_date }}</p>
      <hr />
      <br />
      <center>
      	<img src = "{{ blog.image.url }}"  height=”300” width=”400”/>
      </center>
<br />
      <br/>
      <p>{{ blog.body }}</p>
      <p>{{ blog.update_at }}</p>
      <p>{{ blog.Developing_at }}</p>
      <p>{{ blog.Piloting_at }}</p>
      <p>{{ blog.Debug_at }}</p>
      <p>{{ blog.Ready_at }}</p>

       {% now "Y" %}
  </body>
</html>

templates/core/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login to Forword IT!</title>
    {% include 'includes/stylesheets.html' %}
</head>
<body>

<div class="loader_bg">
    <div class="loader"></div>
</div>

<nav class="navbar navbar-custom navbar-fixed-top">
    <div class="container">
        {% load static %}
              <img src="{% static 'image\logo.PNG' %}" style="width:5%;height:22">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="/"> </a>
        </div>
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <li><a class="navbar-link" href="{% url 'home' %}">Home</a></li>
                <li><a class="navbar-link" href="{% url 'core:register' %}">Register</a></li>





            </ul>
        </div>
    </div>
</nav>

{% block content %}{% endblock %}

<div class="footer-area">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
                <p>&copy;Copyright Forword IT</p>
            </div>
        </div>
    </div>
</div>
{% include 'includes/scripts.html' %}





<div class="container">
    <div class="jumbotron">
      <h1 style="font-size:40px;">Login here!</h1><br>

        <form method="post" action="{% url 'core:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label id="username">Username</label><br>
          <input type="text" name="username" placeholder="" style="resize: vertical; border: 1px solid #ccc;
  border-radius: 9px;
  box-sizing: border-box;"><br>
            <label id="password">Password</label><br>
            <input type="password" name="password" placeholder=""  style="color:black; resize: vertical; border: 1px solid #ccc;
  border-radius: 9px;
  box-sizing: border-box;"><br><br>
<input type="submit" name="" value="Login" style="background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 8px;
  cursor: pointer;" >
</form>

</div>
  </div>


</body>
</html>


<style>




.jumbotron {
  position: absolute;
    left: 13%;
    top: 24%;
    width: 75%;
    text-align: center;
    font-size: 20px;
    padding-top: 30px;
    padding-bottom: 30px;
    margin-bottom: 30px;
    color: inherit;
    background-color: #875690;
    border: 1px solid #ccc;
    border-radius: 9px;
    box-sizing: border-box;
    background-image: url("https://freedesignfile.com/upload/2017/08/Purple-polar-lights-abstract-background-vector.jpg");
}

body {
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 14px;
    line-height: 1.42857143;

        color: #f5f5f5;
    background-color: #fff8d7;
    background-image: url(https://i.redd.it/umpmoneoipn21.jpg);
    }

@media(min-width:768px) {
    .navbar-custom {
        padding: 4px 0;
        border-bottom: 0;
        letter-spacing: 1px;
        background: rgba(0,0,0,.075);
        -webkit-transition: background .5s ease-in-out, padding .5s ease-in-out;
        -moz-transition: background .5s ease-in-out, padding .5s ease-in-out;
        transition: background .5s ease-in-out, padding .5s ease-in-out;
    }
    .navbar-custom.top-nav-collapse {
        -webkit-box-shadow: 0px 0px 2px #777;
        box-shadow: 0px 0px 2px #777;
        background-color: rgba(0, 0, 0, 1);
        box-shadow: 0px 0px 3px rgba(0, 0, 0, 1);
    }
    .navbar-custom.top-nav-collapse .nav li a {
        color: #fff;
    }
    .navbar-custom.top-nav-collapse .nav li.active a {
        background-color: transparent;
        color: #FF0000 !important;
    }
    .navbar-custom.top-nav-collapse .navbar-brand {
        color: #fff;
    }
}


 .navbar-custom .nav li a:hover {
    outline: 0;
    color: rgba(255, 255, 255, .8);
    background-color: #8B008B;
}

   .navbar-custom .nav li a:focus,
   .navbar-custom .nav li a:active {
    outline: 0;
    background-color: transparent;
}


.navbar-custom a {
    color: white;
    font-size: 13px;
    letter-spacing: 0px;
    font-weight: bold;
}
.navbar-custom.navbar-fixed-top.top-nav-collapse {
    background: #48034c;
}

.navbar-custom.top-nav-collapse .nav li a {
    color: #fff;
}

.navbar-custom {
    background: rgba(0,0,0,.075);
    border-bottom: none;
}

.footer-area{

    position: absolute;
    left: 0%;
    top: 92%;
    width: 100%;
    text-align: center;

}
.footer-area {
    background: #48034c;
    padding: 7px 0;
}

input, optgroup, select, textarea {
    margin: 0;
    font: inherit;
    color: black;
}


</style>

templates/core/registration.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ema</title>
    {% include 'includes/stylesheets.html' %}
</head>
<body>

<div class="loader_bg">
    <div class="loader"></div>
</div>

<nav class="navbar navbar-custom navbar-fixed-top">
    <div class="container">
        {% load static %}
              <img src="{% static 'image\lg.png' %}" style="width:5%;height:22">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="/"> </a>
        </div>
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <li><a class="navbar-link" href="{% url 'home' %}">Home</a></li>
                <li><a class="navbar-link" href="{% url 'core:user_login' %}">Login</a></li>





            </ul>
        </div>
    </div>
</nav>

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <div id="snackbar">You are registered</div>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register" style="background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 8px;
  cursor: pointer;">
        </form>

      {% endif %}
    </div>
  </div>

<div class="footer-area">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 text-center">
                <p>&copy;Copyright Ema</p>
            </div>
        </div>
    </div>
</div>
{% include 'includes/scripts.html' %}
<style>


.label {
    display: inline-block;
    max-width: 100%;
    margin-bottom: 5px;
    font-weight: 700;
    color: #191424;
}
p {
    line-height: 26px;
    font-size: 14px;
    font-weight: 400;
    color: #2d2938;
}



.jumbotron {
  position: absolute;
    left: 13%;
    top: 13%;
    width: 75%;
    text-align: left;
    font-size: 20px;
    padding-top: 30px;
    padding-bottom: 30px;
    margin-bottom: 30px;
    color: inherit;
    background-color: #875690;
    border: 1px solid #ccc;
    border-radius: 9px;
    box-sizing: border-box;
    background-image: url("https://cdn.pixabay.com/photo/2016/04/15/04/02/water-1330252_1280.jpg");
}

body {
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 14px;
    line-height: 1.42857143;

        color: #f5f5f5;
    background-color: #fff8d7;
    background-image: url("https://cdn.pixabay.com/photo/2013/02/21/19/10/grass-84622_1280.jpg");
    }

@media(min-width:768px) {
    .navbar-custom {
        padding: 4px 0;
        border-bottom: 0;
        letter-spacing: 1px;
        background: rgba(0,0,0,.075);
        -webkit-transition: background .5s ease-in-out, padding .5s ease-in-out;
        -moz-transition: background .5s ease-in-out, padding .5s ease-in-out;
        transition: background .5s ease-in-out, padding .5s ease-in-out;
    }
    .navbar-custom.top-nav-collapse {
        -webkit-box-shadow: 0px 0px 2px #777;
        box-shadow: 0px 0px 2px #777;
        background-color: rgba(0, 0, 0, 1);
        box-shadow: 0px 0px 3px rgba(0, 0, 0, 1);
    }
    .navbar-custom.top-nav-collapse .nav li a {
        color: #fff;
    }
    .navbar-custom.top-nav-collapse .nav li.active a {
        background-color: transparent;
        color: #FF0000 !important;
    }
    .navbar-custom.top-nav-collapse .navbar-brand {
        color: #fff;
    }
}


 .navbar-custom .nav li a:hover {
    outline: 0;
    color: rgba(255, 255, 255, .8);
    background-color: #8B008B;
}

   .navbar-custom .nav li a:focus,
   .navbar-custom .nav li a:active {
    outline: 0;
    background-color: transparent;
}


.navbar-custom a {
    color: white;
    font-size: 13px;
    letter-spacing: 0px;
    font-weight: bold;
}
.navbar-custom.navbar-fixed-top.top-nav-collapse {
    background: #48034c;
}

.navbar-custom.top-nav-collapse .nav li a {
    color: #fff;
}

.navbar-custom {
    background: rgba(0,0,0,.075);
    border-bottom: none;
}

.footer-area{

    position: fixed;
    left: 0%;
    top: 92%;
    width: 100%;
    text-align: center;

}
.footer-area {
    background: #48034c;
    padding: 7px 0;
}

input, optgroup, select, textarea {
    margin: 0;
    font: inherit;
    color: black;
}
#snackbar {

  text-align: center; /* Centered text */

}


</style>
{% endblock %}